_BASE_: "Base-SOTR.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
    DEFORM_ON_PER_STAGE: [False, True, True, True]
    DEFORM_MODULATED: True
    DEFORM_INTERVAL: 3
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 300000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800, 1024)
  MAX_SIZE_TRAIN: 2048
  MIN_SIZE_TEST: 1000
  MASK_FORMAT: "bitmask"
  
OUTPUT_DIR: "output/SOTR_R101_DCN"
